<!-- fullcalendar css -->



<!--<link href="--><?//=asset('/plugins/fullcalendar-3.9.0/css/fullcalendar.print.css')?><!--" rel="stylesheet" media="print">-->
<!--<link href="--><?//=asset('/plugins/fullcalendar-3.9.0/css/fullcalendar.css')?><!--" rel="stylesheet">-->
<!-- moment js -->
<!--<script src="--><?//=asset('/plugins/fullcalendar-3.9.0/lib/jquery-ui.min.js')?><!--"></script>-->
<!--<script src="--><?//=asset('/plugins/fullcalendar-3.9.0/lib/moment.min.js')?><!--"></script>-->
<!-- fullcalendar js -->
<!--<script src="--><?//=asset('/plugins/fullcalendar-3.9.0/fullcalendar.js')?><!--"></script>-->
<!--<script src="--><?//=asset('/plugins/fullcalendar-3.9.0/locale-all.js')?><!--"></script>-->

<?php if($include_gcal):?>
<script src="<?=asset('/plugins/fullcalendar-3.9.0/gcal.js')?>"></script>
<?php endif;


